@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #000000
skinparam ObjectFontColor #000000
skinparam ObjectBorderColor #000000
skinparam ObjectBackgroundColor #FFFFAA
show member
hide empty member

title "       After command "list s/beginner s/expert""

Object "<u>m:ModelManager</u>" as modelManager
Object "<u>filteredList:FilteredList</u>" as filteredList

Object "<u>alex:Person</u>" as alex {
    skill = "Beginner"
}

Object "<u>charlie:Person</u>" as charlie {
    skill = "Expert"
}

alex -up- filteredList
charlie -up- filteredList
filteredList -up- modelManager

@enduml
