@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
skinparam ranksep 35
skinparam nodesep 35
top to bottom direction

skinparam class<<spacer>> {
BorderColor transparent
BackgroundColor transparent
FontColor transparent
StereotypeFontColor transparent
}

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class UserPrefsSpacer <<spacer>>
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class AddressBookLoadResult
Class InvalidPersonRecord
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager --> "1" UserPrefsStorage
StorageManager --> "1" AddressBookStorage

Storage --|> UserPrefsStorage
Storage -left-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonAddressBookStorage ..> AddressBookLoadResult
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableAddressBook --> "*" InvalidPersonRecord
InvalidPersonRecord --> "1" JsonAdaptedPerson

StorageManager -[hidden]down-> UserPrefsSpacer
UserPrefsSpacer -[hidden]down-> UserPrefsStorage

@enduml
