@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
UniquePersonList -right-> Person

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
Person *--> "1" Skill
Person *--> "1..7" Timeslot
Timeslot --> "1" Day
Timeslot --> "1..12" Slot
Person *--> "1" TrainingGoal
Person *--> "1" InjuryStatus
Person *--> "1" ProgressRecord
@enduml
