@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

show member
hide empty member
title "Final State"
Class "<u>:CommandBox" as CommandBox
Class "<u>:CommandHistory" as CommandHistory {
    commandHistory = [\n\t"help",\n\t"list", \n\t"list s/advancd",\n\t"list s/advanced",\n\t"list"]
    current = 5
}
CommandBox -- CommandHistory
@enduml
