@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

show member
hide empty member
title "Going forward 1 command"
Class "<u>:CommandBox" as CommandBox
Class "<u>:CommandHistory" as CommandHistory {
    commandHistory = [\n\t"help",\n\t"<b>list</b>", \n\t"list s/advancd",\n\t"list s/advanced"]
    current = 1
}
CommandBox -- CommandHistory
@enduml
